[package]
name = "wgui-ttf"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.92"
ttf-parser = "0.20.0"
console_error_panic_hook = "0.1.2"
js-sys = "0.3.69"
potpack = "0.1.2"
